name: CI/CD

on:
  push:
    branches:
      - main # Triggers on direct pushes to the develop branch
  pull_request:
    types: [closed] # Triggers when a pull request targeting develop is closed (merged)
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Uses a fresh Ubuntu environment for each job run

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to check out your repository code
        with:
          fetch-depth: 0 # Fetch all history for git operations like committing and pushing

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Action to set up Docker Buildx for advanced build features

      - name: Login to DockerHub
        uses: docker/login-action@v3 # Action to log in to Docker Hub or another container registry
        with:
          registry: registry.gregdev.dev 
          username: ${{ secrets.DOCKER_USERNAME }} # Your Docker Hub username stored as a GitHub secret
          password: ${{ secrets.DOCKER_PASSWORD }} # Your Docker Hub password/token stored as a GitHub secret

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5 # Action to build and push Docker images
        with:
          context: . # The build context is the root of your repository
          push: true 
          tags: |
            registry.gregdev.dev/library/cosign-key:latest
